import { useAppContext } from '../context/AppContext';

const categoryTranslations: Record<'en' | 'es', Record<string, string>> = {
  en: {
    'Shelter': 'Shelter',
    'Food': 'Food',
    'Clothes': 'Clothes',
    'Supplies': 'Supplies',
    'Health': 'Health',
    'Animals': 'Animals',
    'NA': 'N/A',
    'Wifi/Charging': 'Wifi/Charging',
    'Laundry': 'Laundry',
    'Transportation': 'Transportation',
    'Insurance': 'Insurance',
    'Information': 'Information',
    'Other': 'Other',
    'Debris Removal': 'Debris Removal',
    'Fooe': 'Food',
    'Restaurant': 'Restaurant',
    'Nonprofit': 'Nonprofit',
    'Community Group': 'Community Group',
    'Animal Hospital': 'Animal Hospital',
    'Pasadena Community Job Center': 'Pasadena Community Job Center',
    'Pasadena Sierra Madre': 'Pasadena Sierra Madre',
    'Downtown LA': 'Downtown LA',
    'Hollywood': 'Hollywood',
    'West LA': 'West LA',
    'Echo Park': 'Echo Park',
    'City of LA': 'City of LA',
    'Walmart Baldwin Park': 'Walmart Baldwin Park',
    'Bailey Human Care Center': 'Bailey Human Care Center',
    'Belle\'s Boarding': 'Belle\'s Boarding',
    'Stoner Recreation Center': 'Stoner Recreation Center',
    'Calvary Community Church': 'Calvary Community Church',
    'Lahaina': 'Lahaina',
    'Kahului': 'Kahului',
    'Wailuku': 'Wailuku',
    'Kihei': 'Kihei',
    'Makawao': 'Makawao',
    'Kahului Airport': 'Kahului Airport',
    'Lahaina Civic Center': 'Lahaina Civic Center',
    'Hana': 'Hana',
    'Downtown Asheville': 'Downtown Asheville',
    'West Asheville': 'West Asheville',
    'River Arts District': 'River Arts District',
    'South Asheville': 'South Asheville',
    'East Asheville': 'East Asheville',
    'Central Asheville': 'Central Asheville',
    'North Asheville': 'North Asheville',
    'South Slope': 'South Slope',
    'Montford': 'Montford',
    'Downtown Transit Center': 'Downtown Transit Center',
    'East End': 'East End',
    'City Hall': 'City Hall',
    'Downtown': 'Downtown',
    'Tampa': 'Tampa',
    'Clearwater': 'Clearwater',
    'St. Petersburg': 'St. Petersburg',
    'Canoga Park SDA Church': 'Canoga Park SDA Church',
    'Tujunga Methodist Church': 'Tujunga Methodist Church',
    'Metro LA Evacuation Transit': 'Metro LA Evacuation Transit',
    'Sinai Animal Hospital Center': 'Sinai Animal Hospital Center',
    'Lahaina Community Shelter': 'Lahaina Community Shelter',
    'Maui Strong Shelter': 'Maui Strong Shelter',
    'Maui Food Bank': 'Maui Food Bank',
    'Mission Haven Shelter': 'Mission Haven Shelter',
    'Asheville Food Bank': 'Asheville Food Bank',
    'AVL Shuttle Services': 'AVL Shuttle Services',
    'Bay Area Relief Shelter': 'Bay Area Relief Shelter',
    'Red Cross': 'Red Cross',
    'LA Family Housing': 'LA Family Housing',
    'Little Nelly Burbank': 'Little Nelly Burbank',
    'The Harvest Academy': 'The Harvest Academy',
    'Salvation Army': 'Salvation Army',
    'Los Angeles Food Bank': 'Los Angeles Food Bank',
    'American Legion': 'American Legion',
    'Chinatown Service Center': 'Chinatown Service Center',
    'LaBelle Foundation': 'LaBelle Foundation',
    'National Day Laborer': 'National Day Laborer',
    'YMCA': 'YMCA',
    'LA Community Relief Hub': 'LA Community Relief Hub',
    'Fresh Spin Laundry Relief': 'Fresh Spin Laundry Relief',
    'Safe Harbor Insurance Help Center': 'Safe Harbor Insurance Help Center',
    'InfoLink LA Fire Updates': 'InfoLink LA Fire Updates',
    'Island Nourish': 'Island Nourish',
    'Threads of Aloha': 'Threads of Aloha',
    'Maui Mobile Health': 'Maui Mobile Health',
    'Relief Supply Depot': 'Relief Supply Depot',
    'Paws of Maui': 'Paws of Maui',
    'Tech Relief Maui': 'Tech Relief Maui',
    'Clean Start Maui': 'Clean Start Maui',
    'Maui Shuttle Aid': 'Maui Shuttle Aid',
    'Claims Help Hawaii': 'Claims Help Hawaii',
    'Maui Disaster Info Line': 'Maui Disaster Info Line',
    'Aloha Relief Collective': 'Aloha Relief Collective',
    // Asheville Floods Organizations
    'Meals on Relief': 'Meals on Relief',
    'Threads of Hope': 'Threads of Hope',
    'Mountain Health Mobile Unit': 'Mountain Health Mobile Unit',
    'Flood Relief Depot': 'Flood Relief Depot',
    'Asheville Animal Aid': 'Asheville Animal Aid',
    'TechLink Community Hub': 'TechLink Community Hub',
    'SpinCycle Clean Relief': 'SpinCycle Clean Relief',
    'Claims Assistance AVL': 'Claims Assistance AVL',
    'AVL Disaster Info Line': 'AVL Disaster Info Line',
    'Community Builders Network': 'Community Builders Network',
    // Hurricane Milton Organizations
    'Tampa Safe Haven': 'Tampa Safe Haven',
    'Feeding Tampa Bay': 'Feeding Tampa Bay',
    'St. Pete Emergency Meals': 'St. Pete Emergency Meals',
    'Clothes for Hope': 'Clothes for Hope',
    'Tampa Mobile Health': 'Tampa Mobile Health',
    'Hurricane Aid Depot': 'Hurricane Aid Depot',
    'Pet Relief Tampa Bay': 'Pet Relief Tampa Bay',
    'Connect Relief Hub': 'Connect Relief Hub',
    'Spin & Aid': 'Spin & Aid',
    'Milton Shuttle Relief': 'Milton Shuttle Relief',
    'Tampa Insurance Aid': 'Tampa Insurance Aid',
    'Milton Storm Info Line': 'Milton Storm Info Line',
    'Tampa Bay Relief Network': 'Tampa Bay Relief Network',
  },
  es: {
    'Shelter': 'Refugio',
    'Food': 'Comida',
    'Clothes': 'Ropa',
    'Supplies': 'Suministros',
    'Health': 'Salud',
    'Animals': 'Animales',
    'NA': 'N/A',
    'Wifi/Charging': 'Wifi/Carga',
    'Laundry': 'Lavandería',
    'Transportation': 'Transporte',
    'Insurance': 'Seguro',
    'Information': 'Información',
    'Other': 'Otro',
    'Debris Removal': 'Remoción de escombros',
    'Fooe': 'Comida',
    'Restaurant': 'Restaurante',
    'Nonprofit': 'Organización sin fines de lucro',
    'Community Group': 'Grupo Comunitario',
    'Animal Hospital': 'Hospital Veterinario',
    'Pasadena Community Job Center': 'Centro de Trabajo Comunitario de Pasadena',
    'Pasadena Sierra Madre': 'Pasadena Sierra Madre',
    'Downtown LA': 'Downtown de Los Ángeles',
    'Hollywood': 'Hollywood',
    'West LA': 'Oeste de Los Ángeles',
    'Echo Park': 'Echo Park',
    'City of LA': 'Ciudad de Los Ángeles',
    'Walmart Baldwin Park': 'Walmart Baldwin Park',
    'Bailey Human Care Center': 'Centro de Cuidado Humano Bailey',
    'Belle\'s Boarding': 'Alojamiento de Belle',
    'Stoner Recreation Center': 'Centro de Recreación Stoner',
    'Calvary Community Church': 'Iglesia Comunitaria Calvary',
    'Lahaina': 'Lahaina',
    'Kahului': 'Kahului',
    'Wailuku': 'Wailuku',
    'Kihei': 'Kihei',
    'Makawao': 'Makawao',
    'Kahului Airport': 'Aeropuerto Kahului',
    'Lahaina Civic Center': 'Centro Civic de Lahaina',
    'Hana': 'Hana',
    'Downtown Asheville': 'Downtown de Asheville',
    'West Asheville': 'Oeste de Asheville',
    'River Arts District': 'Distrito de Artes del Río',
    'South Asheville': 'Sur de Asheville',
    'East Asheville': 'Este de Asheville',
    'Central Asheville': 'Central de Asheville',
    'North Asheville': 'Norte de Asheville',
    'South Slope': 'Cuesta Sur',
    'Montford': 'Montford',
    'Downtown Transit Center': 'Centro de Transporte Downtown',
    'East End': 'Final de Este',
    'City Hall': 'Ayuntamiento',
    'Downtown': 'Downtown',
    'Tampa': 'Tampa',
    'Clearwater': 'Clearwater',
    'St. Petersburg': 'San Petersburgo',
    'Canoga Park SDA Church': 'Canoga Park SDA Iglesia',
    'Tujunga Methodist Church': 'Tujunga Methodist Iglesia',
    'Metro LA Evacuation Transit': 'Metro LA Evacuación Tránsito',
    'Sinai Animal Hospital Center': 'Sinai Animal Hospital Centro',
    'Lahaina Community Shelter': 'Refugio Comunitario de Lahaina',
    'Maui Strong Shelter': 'Refugio Fuerte de Maui',
    'Maui Food Bank': 'Banco de Alimentos de Maui',
    'Mission Haven Shelter': 'Refugio Misión Haven',
    'Asheville Food Bank': 'Banco de Alimentos de Asheville',
    'AVL Shuttle Services': 'Servicios de Shuttle AVL',
    'Bay Area Relief Shelter': 'Refugio de Ayuda de Área de la Bahía',
    'Red Cross': 'Cruz Roja',
    'LA Family Housing': 'Vivienda Familiar de LA',
    'Little Nelly Burbank': 'Little Nelly Burbank',
    'The Harvest Academy': 'La Academia de la Cosecha',
    'Salvation Army': 'Ejército de Salvación',
    'Los Angeles Food Bank': 'Banco de Alimentos de Los Ángeles',
    'American Legion': 'Legión Americana',
    'Chinatown Service Center': 'Centro de Servicios de Chinatown',
    'LaBelle Foundation': 'Fundación LaBelle',
    'National Day Laborer': 'Trabajador Nacional del Día',
    'YMCA': 'YMCA',
    'LA Community Relief Hub': 'Centro de Ayuda Comunitaria de LA',
    'Fresh Spin Laundry Relief': 'Ayuda de Lavandería Fresh Spin',
    'Safe Harbor Insurance Help Center': 'Centro de Ayuda de Seguros Safe Harbor',
    'InfoLink LA Fire Updates': 'Actualizaciones de Incendios InfoLink LA',
    'Island Nourish': 'Nutrición de la Isla',
    'Threads of Aloha': 'Hilos de Aloha',
    'Maui Mobile Health': 'Salud Móvil de Maui',
    'Relief Supply Depot': 'Depósito de Suministros de Ayuda',
    'Paws of Maui': 'Patas de Maui',
    'Tech Relief Maui': 'Tecnología de Ayuda Maui',
    'Clean Start Maui': 'Comienzo Limpio Maui',
    'Maui Shuttle Aid': 'Ayuda de Transporte de Maui',
    'Claims Help Hawaii': 'Ayuda de Reclamaciones Hawaii',
    'Maui Disaster Info Line': 'Línea de Información de Desastres de Maui',
    'Aloha Relief Collective': 'Colectivo de Ayuda Aloha',
    'Meals on Relief': 'Comidas de Ayuda',
    'Threads of Hope': 'Hilos de Esperanza',
    'Mountain Health Mobile Unit': 'Unidad Móvil de Salud de la Montaña',
    'Flood Relief Depot': 'Depósito de Ayuda contra Inundaciones',
    'Asheville Animal Aid': 'Ayuda Animal de Asheville',
    'TechLink Community Hub': 'Centro Comunitario TechLink',
    'SpinCycle Clean Relief': 'Ayuda Limpia SpinCycle',
    'Claims Assistance AVL': 'Asistencia de Reclamaciones AVL',
    'AVL Disaster Info Line': 'Línea de Información de Desastres AVL',
    'Community Builders Network': 'Red de Constructores Comunitarios',
    'Tampa Safe Haven': 'Refugio Seguro de Tampa',
    'Feeding Tampa Bay': 'Alimentando Tampa Bay',
    'St. Pete Emergency Meals': 'Comidas de Emergencia de San Petersburgo',
    'Clothes for Hope': 'Ropa para la Esperanza',
    'Tampa Mobile Health': 'Salud Móvil de Tampa',
    'Hurricane Aid Depot': 'Depósito de Ayuda del Huracán',
    'Pet Relief Tampa Bay': 'Ayuda para Mascotas Tampa Bay',
    'Connect Relief Hub': 'Centro de Ayuda Connect',
    'Spin & Aid': 'Giro y Ayuda',
    'Milton Shuttle Relief': 'Ayuda de Transporte Milton',
    'Tampa Insurance Aid': 'Ayuda de Seguros de Tampa',
    'Milton Storm Info Line': 'Línea de Información de Tormenta Milton',
    'Tampa Bay Relief Network': 'Red de Ayuda de Tampa Bay',
    'Vitamins, pain meds, bandaids, atacids, baby wipes, canned goods, gatorage, water, fresh produce, toilet paper paper towels, hand soap, dish soap, plates, travel size shampoo, sunscreen, work helmets. NO CLOTHING, SHOES, TOYS': 'Vitaminas, analgésicos, curitas, antiácidos, toallitas para bebés, alimentos enlatados, bebidas deportivas, agua, productos frescos, papel higiénico, toallas de papel, jabón de manos, jabón para platos, platos, champú de viaje, protector solar, cascos de trabajo. NO ROPA, ZAPATOS, JUGUETES',
    'Drivers, fuel cards': 'Conductores, tarjetas de combustible',
    'Batteries, water jugs': 'Baterías, jarras de agua',
    'Sleeping bags, volunteer staff': 'Sacos de dormir, personal voluntario',
    'Meal containers, volunteers': 'Contenedores de comidas, voluntarios',
    'Free clothes for all ages': 'Ropa gratis para todas las edades',
  },
};

const commonPhrasesTranslations: Record<'en' | 'es', Record<string, string>> = {
  en: {
    'Church': 'Church',
    'Transit': 'Transit',
    'Mid-Wilshire': 'Mid-Wilshire',
    'Canoga Park SDA Church': 'Canoga Park SDA Church',
    'Tujunga Methodist Church': 'Tujunga Methodist Church',
    'Metro LA Evacuation Transit': 'Metro LA Evacuation Transit',
    'Sinai Animal Hospital Center': 'Sinai Animal Hospital Center',
    'Meals to first responders & those affected by the fires': 'Meals to first responders & those affected by the fires',
    'Free groceries & toiletries': 'Free groceries & toiletries',
    'Clothes & toiletries': 'Clothes & toiletries',
    'Translation services in Mandarin, Cantonese, Spanish, case management & care coordination, crisis counseling, medical service, support for caregivers': 'Translation services in Mandarin, Cantonese, Spanish, case management & care coordination, crisis counseling, medical service, support for caregivers',
    'Pet boarding need': 'Pet boarding need',
    'pet boarding need': 'pet boarding need',
    'free animal boarding': 'free animal boarding',
    'free animal boarding ': 'free animal boarding',
    'Urgent: crates (small, medium, large); prescription dog food.': 'Urgent: crates (small, medium, large); prescription dog food.',
    'Hygiene Kits: Shampoo, Conditioner, Soap, Toothbrush, Toothpaste, Lotion, Wet wipes, Beanie, Gloves, Snacks, Mini Water Bottle. Not essential, but highly requested: Pads and tampons, Shaving cream and razor, deodorant, bandaids, tissues (individually packaged)': 'Hygiene Kits: Shampoo, Conditioner, Soap, Toothbrush, Toothpaste, Lotion, Wet wipes, Beanie, Gloves, Snacks, Mini Water Bottle. Not essential, but highly requested: Pads and tampons, Shaving cream and razor, deodorant, bandaids, tissues (individually packaged)',
    'Bedding, towels, toiletries, cleaning supplies, and non-perishable foods; Also, monetary donations': 'Bedding, towels, toiletries, cleaning supplies, and non-perishable foods; Also, monetary donations',
    'Urgent: crates (small, medium, large); prescription dog food. Also accepting: first aid kits & medical supplies, cat food (wet preferred), formula (for both cats and dogs), cat supplies (litter boxes and miscellaneous items), pee pads,': 'Urgent: crates (small, medium, large); prescription dog food. Also accepting: first aid kits & medical supplies, cat food (wet preferred), formula (for both cats and dogs), cat supplies (litter boxes and miscellaneous items), pee pads,',
    'Emergency lodging, meals': 'Emergency lodging, meals',
    'Beds, emergency kits': 'Beds, emergency kits',
    'Food packages, meal kits': 'Food packages, meal kits',
    'Prepared meals, fresh produce': 'Prepared meals, fresh produce',
    'Free clothing donations': 'Free clothing donations',
    'Medical checkups, prescription refills': 'Medical checkups, prescription refills',
    'Flashlights, tarps, water': 'Flashlights, tarps, water',
    'Pet shelter, supplies': 'Pet shelter, supplies',
    'Charging stations, free WiFi': 'Charging stations, free WiFi',
    'Free laundry for evacuees': 'Free laundry for evacuees',
    'Shuttles to shelters and clinics': 'Shuttles to shelters and clinics',
    'Claim filing, disaster recovery': 'Claim filing, disaster recovery',
    'News, alerts, coordination': 'News, alerts, coordination',
    'Cots, bottled water': 'Cots, bottled water',
    'Blankets, hygiene supplies': 'Blankets, hygiene supplies',
    'Canned food, volunteers': 'Canned food, volunteers',
    'Coolers, prep volunteers': 'Coolers, prep volunteers',
    'Children\'s clothes, shoes': 'Children\'s clothes, shoes',
    'Bandages, glucose monitors': 'Bandages, glucose monitors',
    'Generators, batteries': 'Generators, batteries',
    'Kennels, food': 'Kennels, food',
    'Cables, power banks': 'Cables, power banks',
    'Soap, dryer sheets': 'Soap, dryer sheets',
    'Fuel vouchers, drivers': 'Fuel vouchers, drivers',
    'Computers, printers': 'Computers, printers',
    'Staff, radios': 'Staff, radios',
    'Temporary housing, hot meals': 'Temporary housing, hot meals',
    'Beds, clothing, warm meals': 'Beds, clothing, warm meals',
    'Food distribution, hot meals': 'Food distribution, hot meals',
    'Meals for evacuees and responders': 'Meals for evacuees and responders',
    'Free clothing for all ages': 'Free clothing for all ages',
    'Basic medical checkups, vaccines': 'Basic medical checkups, vaccines',
    'Bottled water, tarps, flashlights': 'Bottled water, tarps, flashlights',
    'Animal boarding, pet food': 'Animal boarding, pet food',
    'Free charging stations, internet': 'Free charging stations, internet',
    'Free laundry for flood victims': 'Free laundry for flood victims',
    'Free transit to shelters and aid centers': 'Free transit to shelters and aid centers',
    'Filing assistance, damage claims': 'Filing assistance, damage claims',
    'Official announcements, guidance': 'Official announcements, guidance',
    'Sleeping bags, volunteers': 'Sleeping bags, volunteers',
    'Meal containers, fuel cards': 'Meal containers, fuel cards',
    'Coats, children\'s clothes': 'Coats, children\'s clothes',
    'Medical volunteers, first aid kits': 'Medical volunteers, first aid kits',
    'Pet crates, dry food': 'Pet crates, dry food',
    'Power strips, hotspots': 'Power strips, hotspots',
    'Drivers, fuel donations': 'Drivers, fuel donations',
    'Laptops, bilingual staff': 'Laptops, bilingual staff',
    'Call center staff': 'Call center staff',
    'Emergency shelter and meals': 'Emergency shelter and meals',
    'Food boxes, water': 'Food boxes, water',
    'Hot meals and food delivery': 'Hot meals and food delivery',
    'Medical triage, prescriptions': 'Medical triage, prescriptions',
    'Emergency kits, tarps, flashlights': 'Emergency kits, tarps, flashlights',
    'WiFi and phone charging': 'WiFi and phone charging',
    'Free laundry services': 'Free laundry services',
    'Transport to shelters, aid centers': 'Transport to shelters, aid centers',
    'Help filing claims': 'Help filing claims',
    'Live updates, resources': 'Live updates, resources',
    'Non-perishables, bottled water': 'Non-perishables, bottled water',
    'Shoes, new underwear': 'Shoes, new underwear',
    'OTC meds, first aid': 'OTC meds, first aid',
    'Batteries, duct tape': 'Batteries, duct tape',
    'Kennels, leashes': 'Kennels, leashes',
    'Power banks, cords': 'Power banks, cords',
    'Call takers, interpreters': 'Call takers, interpreters',
    'Closed': 'Closed',
    'CLOSED': 'CLOSED',
    'daily': 'daily',
    'TBD': 'TBD',
    'N/A': 'N/A',
    'NA': 'N/A',
    'Overnight shelter, meals, snacks and water; health services (for disaster-related conditions), such as first aid, refilling lost prescriptions or replacing lost eyeglasses; emotional support and mental health services; spiritual care; help reconnecting with loved ones; information about disaster-related resources in the community.': 'Overnight shelter, meals, snacks and water; health services (for disaster-related conditions), such as first aid, refilling lost prescriptions or replacing lost eyeglasses; emotional support and mental health services; spiritual care; help reconnecting with loved ones; information about disaster-related resources in the community.',
    'Partnership with Redcross and LA county Officials: Shelter for Refugees. Hosting Firefighters to be able to sleep and Shower. A safe and secure place to sit, work, charge devices, or access WiFi to come to our church campus. Facility is currently available to accommodate this need and anyone is welcome to come today through Thursday.': 'Partnership with Redcross and LA county Officials: Shelter for Refugees. Hosting Firefighters to be able to sleep and Shower. A safe and secure place to sit, work, charge devices, or access WiFi to come to our church campus. Facility is currently available to accommodate this need and anyone is welcome to come today through Thursday.',
    'Community coordination, volunteers': 'Community coordination, volunteers',
    'Flyers, leaders': 'Flyers, leaders',
    'Meals to first responders & those affected by the fires.': 'Meals to first responders & those affected by the fires.',
    'Non-perishable food and water.': 'Non-perishable food and water.',
    'Partnership with Redcross and LA county officials. Shelter for refugees. Hosting firefighters to be able to sleep and shower. A safe and secure place to sit, work, charge devices, or access WiFi. Facility is currently available, and anyone is welcome to come today through Thursday.': 'Partnership with Redcross and LA county officials. Shelter for refugees. Hosting firefighters to be able to sleep and shower. A safe and secure place to sit, work, charge devices, or access WiFi. Facility is currently available, and anyone is welcome to come today through Thursday.',
    'Shelter for evacuees.': 'Shelter for evacuees.',
    'Housing for evacuees.': 'Housing for evacuees.',
    'Food for evacuees and first responders.': 'Food for evacuees and first responders.',
    'Sheets, towels, toiletries, and non-perishable food.': 'Sheets, towels, toiletries, and non-perishable food.',
    'Hygiene Kits: shampoo, conditioner, soap, toothbrush, toothpaste, lotion, wet wipes, beanie, gloves, snacks, mini water bottle. Not essential, but highly requested: pads and tampons, shaving cream and razor, deodorant, bandaids, tissues (individually packaged).': 'Hygiene Kits: shampoo, conditioner, soap, toothbrush, toothpaste, lotion, wet wipes, beanie, gloves, snacks, mini water bottle. Not essential, but highly requested: pads and tampons, shaving cream and razor, deodorant, bandaids, tissues (individually packaged).',
    'Bedding, towels, toiletries, cleaning supplies, and non-perishable foods; Also accpeting monetary donations': 'Bedding, towels, toiletries, cleaning supplies, and non-perishable foods; Also accpeting monetary donations',
    'Free animal boarding.': 'Free animal boarding.',
    'Blankets, hygiene kits': 'Blankets, hygiene kits',
    'Water jugs': 'Water jugs',
    'Detergent, dryer sheets': 'Detergent, dryer sheets',
    'Volunteer coordination, neighborhood support': 'Volunteer coordination, neighborhood support',
    'Volunteer captains, flyers': 'Volunteer captains, flyers',
    'Temporary beds, hot meals': 'Temporary beds, hot meals',
    'Volunteer staff': 'Volunteer staff',
    'Printers, laptops': 'Printers, laptops',
    'Community coordination, aid triage': 'Community coordination, aid triage',
    'Volunteer leaders, supplies': 'Volunteer leaders, supplies',
    'Baby wipes, canned goods, gatorades, water, fresh produce, toilet paper, paper towels, hand soap, dish soap, plates, travel size shampoo, bandaids, sunscreen, work helmets, vitamins, OTC meds': 'Baby wipes, canned goods, gatorades, water, fresh produce, toilet paper, paper towels, hand soap, dish soap, plates, travel size shampoo, bandaids, sunscreen, work helmets, vitamins, OTC meds',
    'Non-perishable snacks, water, hygine supplies (women\'s deoderant, pads, hand soap), laundry supplies, cleaning supplies, pet food/supplies, baby diapers size 6&7, baby wiper, bags, tarps': 'Non-perishable snacks, water, hygine supplies (women\'s deoderant, pads, hand soap), laundry supplies, cleaning supplies, pet food/supplies, baby diapers size 6&7, baby wiper, bags, tarps',
    'Vitamins, pain meds, bandaids, atacids, baby wipes, canned goods, gatorage, water, fresh produce, toilet paper paper towels, hand soap, dish soap, plates, travel size shampoo, sunscreen, work helmets. NO CLOTHING, SHOES, TOYS': 'Vitamins, pain meds, bandaids, atacids, baby wipes, canned goods, gatorage, water, fresh produce, toilet paper paper towels, hand soap, dish soap, plates, travel size shampoo, sunscreen, work helmets. NO CLOTHING, SHOES, TOYS',
    'Batteries, water jugs': 'Batteries, water jugs',
    'Sleeping bags, volunteer staff': 'Sleeping bags, volunteer staff',
    'Meal containers, volunteers': 'Meal containers, volunteers',
  },
  es: {
    'Church': 'Iglesia',
    'Transit': 'Tránsito',
    'Mid-Wilshire': 'Mid-Wilshire',
    'Canoga Park SDA Church': 'Canoga Park SDA Iglesia',
    'Tujunga Methodist Church': 'Tujunga Methodist Iglesia',
    'Metro LA Evacuation Transit': 'Metro LA Evacuación Tránsito',
    'Sinai Animal Hospital Center': 'Sinai Animal Hospital Centro',
    'Meals to first responders & those affected by the fires': 'Comidas para socorristas y afectados por los incendios',
    'Free groceries & toiletries': 'Comestibles y artículos de aseo gratuitos',
    'Urgent: crates (small, medium, large); prescription dog food.': 'Urgente: jaulas (pequeñas, medianas, grandes); comida para perros con receta.',
    'Hygiene Kits: Shampoo, Conditioner, Soap, Toothbrush, Toothpaste, Lotion, Wet wipes, Beanie, Gloves, Snacks, Mini Water Bottle. Not essential, but highly requested: Pads and tampons, Shaving cream and razor, deodorant, bandaids, tissues (individually packaged)': 'Kits de higiene: champú, acondicionador, jabón, cepillo de dientes, pasta de dientes, loción, toallitas húmedas, gorro, guantes, bocadillos, botella de agua pequeña. No esencial, pero muy solicitado: toallas y tampones, crema y rasuradora, desodorante, curitas, pañuelos (empaquetados individualmente)',
    'Translation services in Mandarin, Cantonese, Spanish, case management & care coordination, crisis counseling, medical service, support for caregivers': 'Servicios de traducción en mandarín, cantonés, español, gestión de casos y coordinación de atención, consejería de crisis, servicio médico, apoyo para cuidadores',
    'Bedding, towels, toiletries, cleaning supplies, and non-perishable foods; Also accpeting monetary donations': 'Ropa de cama, toallas, artículos de aseo, suministros de limpieza y alimentos no perecederos; también se aceptan donaciones monetarias',
    'Baby wipes, canned goods, gatorades, water, fresh produce, toilet paper, paper towels, hand soap, dish soap, plates, travel size shampoo, bandaids, sunscreen, work helmets, vitamins, OTC meds': 'Toallitas para bebés, alimentos enlatados, bebidas deportivas, agua, productos frescos, papel higiénico, toallas de papel, jabón de manos, jabón para platos, platos, champú de viaje, curitas, protector solar, cascos de trabajo, vitaminas, medicamentos de venta libre',
    'Vitamins, pain meds, bandaids, atacids, baby wipes, canned goods, gatorage, water, fresh produce, toilet paper paper towels, hand soap, dish soap, plates, travel size shampoo, sunscreen, work helmets. NO CLOTHING, SHOES, TOYS': 'Vitaminas, analgésicos, curitas, antiácidos, toallitas para bebés, alimentos enlatados, bebidas deportivas, agua, productos frescos, papel higiénico, toallas de papel, jabón de manos, jabón para platos, platos, champú de viaje, protector solar, cascos de trabajo. NO ROPA, ZAPATOS, JUGUETES',
    'Non-perishable snacks, water, hygine supplies (women\'s deoderant, pads, hand soap), laundry supplies, cleaning supplies, pet food/supplies, baby diapers size 6&7, baby wiper, bags, tarps': 'Bocadillos no perecederos, agua, suministros de higiene (desodorante femenino, toallas sanitarias, jabón de manos), suministros de lavandería, suministros de limpieza, comida/suministros para mascotas, pañales talla 6 y 7, toallitas para bebés, bolsas, lonas',
    'Free Wi-Fi, phone charging, disaster info desk': 'Wi-Fi gratis, carga de teléfonos, mesa de información sobre desastres',
    'Volunteers, extension cords': 'Voluntarios, cables de extensión',
    'Detergent, volunteers': 'Detergente, voluntarios',
    'Claims support, paperwork assistance': 'Asistencia con reclamaciones, ayuda con papeleo',
    'Laptops, printers': 'Laptops, impresoras',
    'Evacuation shuttles, route info': 'Transporte de evacuación, información de rutas',
    'Drivers, gas cards': 'Conductores, tarjetas de gasolina',
    'Real-time updates, aid navigation': 'Actualizaciones en tiempo real, navegación de ayuda',
    'Flyers, interpreters': 'Volantes, intérpretes',
    'Emergency lodging, meals': 'Alojamiento de emergencia, comidas',
    'Beds, emergency kits': 'Camas, kits de emergencia',
    'Food packages, meal kits': 'Paquetes de alimentos, kits de comidas',
    'Prepared meals, fresh produce': 'Comidas preparadas, productos frescos',
    'Free clothing donations': 'Donaciones de ropa gratis',
    'Medical checkups, prescription refills': 'Chequeos médicos, reposición de recetas',
    'Flashlights, tarps, water': 'Linternas, lonas, agua',
    'Pet shelter, supplies': 'Refugio para mascotas, suministros',
    'Charging stations, free WiFi': 'Estaciones de carga, WiFi gratis',
    'Free laundry for evacuees': 'Lavandería gratuita para evacuados',
    'Shuttles to shelters and clinics': 'Transporte a refugios y clínicas',
    'Claim filing, disaster recovery': 'Presentación de reclamaciones, recuperación ante desastres',
    'News, alerts, coordination': 'Noticias, alertas, coordinación',
    'Cots, bottled water': 'Catres, agua embotellada',
    'Blankets, hygiene supplies': 'Mantas, suministros de higiene',
    'Canned food, volunteers': 'Comida enlatada, voluntarios',
    'Coolers, prep volunteers': 'Neveras, voluntarios de preparación',
    'Children\'s clothes, shoes': 'Ropa de niños, zapatos',
    'Bandages, glucose monitors': 'Vendajes, monitores de glucosa',
    'Generators, batteries': 'Generadores, baterías',
    'Kennels, food': 'Perreras, comida',
    'Cables, power banks': 'Cables, bancos de energía',
    'Soap, dryer sheets': 'Jabón, hojas para secadora',
    'Fuel vouchers, drivers': 'Vales de combustible, conductores',
    'Computers, printers': 'Computadoras, impresoras',
    'Staff, radios': 'Personal, radios',
    'Temporary housing, hot meals': 'Vivienda temporal, comidas calientes',
    'Beds, clothing, warm meals': 'Camas, ropa, comidas calientes',
    'Food distribution, hot meals': 'Distribución de alimentos, comidas calientes',
    'Meals for evacuees and responders': 'Comidas para evacuados y socorristas',
    'Free clothing for all ages': 'Ropa gratis para todas las edades',
    'Basic medical checkups, vaccines': 'Chequeos médicos básicos, vacunas',
    'Bottled water, tarps, flashlights': 'Agua embotellada, lonas, linternas',
    'Animal boarding, pet food': 'Alojamiento de mascotas, comida para mascotas',
    'Free charging stations, internet': 'Estaciones de carga gratuitas, internet',
    'Free laundry for flood victims': 'Lavandería gratuita para víctimas de inundaciones',
    'Free transit to shelters and aid centers': 'Transporte gratuito a refugios y centros de ayuda',
    'Filing assistance, damage claims': 'Asistencia para presentar reclamaciones de daños',
    'Official announcements, guidance': 'Anuncios oficiales, orientación',
    'Sleeping bags, volunteers': 'Sacos de dormir, voluntarios',
    'Meal containers, fuel cards': 'Contenedores de comida, tarjetas de combustible',
    'Coats, children\'s clothes': 'Abrigos, ropa de niños',
    'Medical volunteers, first aid kits': 'Voluntarios médicos, kits de primeros auxilios',
    'Pet crates, dry food': 'Jaulas para mascotas, comida seca',
    'Power strips, hotspots': 'Regletas, puntos de acceso',
    'Drivers, fuel donations': 'Conductores, donaciones de combustible',
    'Laptops, bilingual staff': 'Laptops, personal bilingüe',
    'Call center staff': 'Personal del centro de llamadas',
    'Emergency shelter and meals': 'Refugio de emergencia y comidas',
    'Food boxes, water': 'Cajas de comida, agua',
    'Hot meals and food delivery': 'Comidas calientes y entrega de alimentos',
    'Medical triage, prescriptions': 'Triage médico, recetas',
    'Emergency kits, tarps, flashlights': 'Kits de emergencia, lonas, linternas',
    'WiFi and phone charging': 'WiFi y carga de teléfonos',
    'Free laundry services': 'Servicios de lavandería gratuitos',
    'Transport to shelters, aid centers': 'Transporte a refugios, centros de ayuda',
    'Help filing claims': 'Ayuda para presentar reclamaciones',
    'Live updates, resources': 'Actualizaciones en vivo, recursos',
    'Non-perishables, bottled water': 'No perecederos, agua embotellada',
    'Shoes, new underwear': 'Zapatos, ropa interior nueva',
    'OTC meds, first aid': 'Medicamentos de venta libre, primeros auxilios',
    'Batteries, duct tape': 'Baterías, cinta adhesiva',
    'Kennels, leashes': 'Perreras, correas',
    'Power banks, cords': 'Bancos de energía, cables',
    'Call takers, interpreters': 'Operadores, intérpretes',
    'Closed': 'Cerrado',
    'CLOSED': 'CERRADO',
    'daily': 'diario',
    'TBD': 'Por determinar',
    'N/A': 'No disponible',
    'NA': 'No disponible',
    'Overnight shelter, meals, snacks and water; health services (for disaster-related conditions), such as first aid, refilling lost prescriptions or replacing lost eyeglasses; emotional support and mental health services; spiritual care; help reconnecting with loved ones; information about disaster-related resources in the community.': 'Refugio nocturno, comidas, bocadillos y agua; servicios de salud (para condiciones relacionadas con desastres), como primeros auxilios, reposición de recetas perdidas o reemplazo de anteojos perdidos; apoyo emocional y servicios de salud mental; cuidado espiritual; ayuda para reconectar con seres queridos; información sobre recursos relacionados con desastres en la comunidad.',
    'Partnership with Redcross and LA county Officials: Shelter for Refugees. Hosting Firefighters to be able to sleep and Shower. A safe and secure place to sit, work, charge devices, or access WiFi to come to our church campus. Facility is currently available to accommodate this need and anyone is welcome to come today through Thursday.': 'Asociación con la Cruz Roja y funcionarios del condado de LA: Refugio para refugiados. Alojamiento de bomberos para poder dormir y ducharse. Un lugar seguro y protegido para sentarse, trabajar, cargar dispositivos o acceder a WiFi para venir a nuestro campus de la iglesia. La instalación está actualmente disponible para satisfacer esta necesidad y cualquiera es bienvenido a venir hoy hasta el jueves.',
    'Community coordination, volunteers': 'Coordinación comunitaria, voluntarios',
    'Flyers, leaders': 'Volantes, líderes',
    'Meals to first responders & those affected by the fires.': 'Comidas para socorristas y afectados por los incendios.',
    'Non-perishable food and water.': 'Alimentos no perecederos y agua.',
    'Partnership with Redcross and LA county officials. Shelter for refugees. Hosting firefighters to be able to sleep and shower. A safe and secure place to sit, work, charge devices, or access WiFi. Facility is currently available, and anyone is welcome to come today through Thursday.': 'Asociación con la Cruz Roja y funcionarios del condado de LA. Refugio para refugiados. Alojamiento de bomberos para poder dormir y ducharse. Un lugar seguro y protegido para sentarse, trabajar, cargar dispositivos o acceder a WiFi. La instalación está disponible actualmente, y cualquiera es bienvenido a venir desde hoy hasta el jueves.',
    'Shelter for evacuees.': 'Refugio para evacuados.',
    'Housing for evacuees.': 'Vivienda para evacuados.',
    'Food for evacuees and first responders.': 'Comida para evacuados y socorristas.',
    'Sheets, towels, toiletries, and non-perishable food.': 'Sábanas, toallas, artículos de aseo y alimentos no perecederos.',
    'Clothes & toiletries': 'Ropa y artículos de aseo',
    'Hygiene Kits: shampoo, conditioner, soap, toothbrush, toothpaste, lotion, wet wipes, beanie, gloves, snacks, mini water bottle. Not essential, but highly requested: pads and tampons, shaving cream and razor, deodorant, bandaids, tissues (individually packaged).': 'Kits de higiene: champú, acondicionador, jabón, cepillo de dientes, pasta de dientes, loción, toallitas húmedas, gorro, guantes, bocadillos, botella de agua pequeña. No esencial, pero muy solicitado: toallas sanitarias y tampones, crema de afeitar y navaja, desodorante, curitas, pañuelos (empaquetados individualmente).',
    'Free animal boarding.': 'Alojamiento gratuito para animales.',
    'Blankets, hygiene kits': 'Mantas, kits de higiene',
    'Water jugs': 'Jarras de agua',
    'Detergent, dryer sheets': 'Detergente, hojas para secadora',
    'Volunteer coordination, neighborhood support': 'Coordinación de voluntarios, apoyo vecinal',
    'Volunteer captains, flyers': 'Capitanes voluntarios, volantes',
    'Temporary beds, hot meals': 'Camas temporales, comidas calientes',
    'Volunteer staff': 'Personal voluntario',
    'Free clothes for all ages': 'Ropa gratis para todas las edades',
    'Printers, laptops': 'Impresoras, laptops',
    'Community coordination, aid triage': 'Coordinación comunitaria, clasificación de ayuda',
    'Volunteer leaders, supplies': 'Líderes voluntarios, suministros',
    'Pet boarding need': 'Necesidad de alojamiento para mascotas',
    'Batteries, water jugs': 'Baterías, jarras de agua',
    'Sleeping bags, volunteer staff': 'Sacos de dormir, personal voluntario',
    'Meal containers, volunteers': 'Contenedores de comidas, voluntarios',
  },
};

function normalize(str: string) {
  return str.replace(/\\s+/g, ' ').trim();
}

export const translateData = (data: any, language: 'en' | 'es'): any => {
  if (!data) {return data;}
  if (typeof data === 'string') {
    if (categoryTranslations[language][data]) {
      return categoryTranslations[language][data];
    }
    if (commonPhrasesTranslations[language][data]) {
      return commonPhrasesTranslations[language][data];
    }
    const normalizedInput = normalize(data);
    for (const key in commonPhrasesTranslations[language]) {
      if (normalize(key) === normalizedInput) {
        return commonPhrasesTranslations[language][key];
      }
    }
    return data;
  }
  if (Array.isArray(data)) {
    return data.map(item => translateData(item, language));
  }
  if (typeof data === 'object') {
    const translated: any = {};
    for (const key in data) {
      translated[key] = translateData(data[key], language);
    }
    return translated;
  }
  return data;
};

export const useTranslatedData = (data: any) => {
  const { language } = useAppContext();
  return translateData(data, language);
};
